language: php

php:
  - '7.2'
  - '7.3'

services:
  - elasticsearch

matrix:
  allow_failures:
    - php: '7.3'
      env: COMPOSER_FLAGS="--prefer-lowest"

env:
  matrix:
    - COMPOSER_FLAGS=""
    - COMPOSER_FLAGS="--prefer-lowest"

cache:
  directories:
    - $HOME/.composer/cache/files

notifications:
  email: false

install:
  - composer self-update
  - composer update $COMPOSER_FLAGS

script: make test
