language: php

php:
  - 5.6
  - 5.5

services:
  - elasticsearch

notifications:
  email:
    recipients:
      - tech@pmg.co
    on_success: change
    on_failure: always

install: composer install --prefer-source
script: make test
